version: '3'
services:
  postgres:
    image: "postgres:12.5"
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      DATABASE_HOST: "172.19.0.2"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "art-gallery"
  api:
    # somewhere we need to run ts-node /usr/local/bin/typeorm migration:generate -n initTables

    container_name: api
    restart: always
    build: ./api

    # this is where we host the development platform image
    image: art-gallery_api
    volumes:
      
      # so they persist across container restarts
      - ./api:/usr/app
      -  /usr/app/node_modules

    environment:
      DATABASE_HOST: "172.19.0.2"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "art-gallery"
    ports:
      - "3001:3000"
      # - "5432:5432"
    links:
      - postgres
  client:
    container_name: client
    restart: always
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    links:
      - "api"
networks:
  default:
    external:
      name: art-gallery
