version: '3'
services:
  postgres:
    image: "postgres:9.6.1"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
  api:
    container_name: api
    restart: always
    build: ./api

    # this is where we host the development platform image
    image: art-gallery_api
    volumes:
 
      # so they persist across container restarts
      - ./api:/usr/app
      -  /usr/app/node_modules
    ports:
      - "3000:3000"
    links:
      - postgres
